name: Acceptance tests
on:
  workflow_dispatch:
  push:
    branches:
      - 'staging'
      - 'main'
  pull_request:
    branches:
      - 'staging'
      - 'main'
    types:
      - assigned
      - opened
      - synchronize
      - reopened
      - edited
      - ready_for_review
  schedule:
      - cron: '0 12 * * *' # This will run the workflow every day at 00:00 UTC

concurrency:
  group: testing-concurrency-group
  cancel-in-progress: false

jobs:
  enterprise:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      - name: Build and run dev container task
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/aimoda/terraform-provider-corellium-devcontainer
          cacheFrom: ghcr.io/aimoda/terraform-provider-corellium-devcontainer
          push: never
          runCmd: |
            export CORELLIUM_API_TOKEN=${{ secrets.CORELLIUM_API_TOKEN }}
            export CORELLIUM_API_HOST=${{ vars.CORELLIUM_API_HOST }}
            go get
            go mod tidy
            make install
            make testacc
  non-enterprise:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      - name: Build and run dev container task
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/aimoda/terraform-provider-corellium-devcontainer
          cacheFrom: ghcr.io/aimoda/terraform-provider-corellium-devcontainer
          push: never
          runCmd: |
            export CORELLIUM_API_TOKEN=${{ secrets.CORELLIUM_API_TOKEN_PERSONAL }}
            export CORELLIUM_API_HOST=${{ vars.CORELLIUM_API_HOST }}
            go get
            go mod tidy
            make install
            NON_ENTERPRISE=1 make testacc
