name: Dev Container Build
on:
  workflow_dispatch:
  push:
  pull_request:
    branches:
      - 'staging'
      - 'main'
  schedule:
      - cron: '0 12 * * *' # This will run the workflow every day at 00:00 UTC
concurrency:
  group: devcontainer-build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      - name: Build and run dev container task
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/aimoda/terraform-provider-corellium-devcontainer
          cacheFrom: ghcr.io/aimoda/terraform-provider-corellium-devcontainer
          push: never
          runCmd: |
            export CORELLIUM_API_TOKEN=${{ secrets.CORELLIUM_API_TOKEN }}
            go get
            go mod tidy
            make install
            make test
            make testacc