name: Dev Container Build
on:
  workflow_dispatch:
  push:
  pull_request:
    branches:
      - 'staging'
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      - name: Build and run dev container task
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/aimoda/terraform-provider-corellium-devcontainer
          cacheFrom: ghcr.io/aimoda/terraform-provider-corellium-devcontainer
          push: never
          # refFilterForPush: refs/heads/main
          # eventFilterForPush: push
        #   # Change this to be your CI task/script
        #   runCmd: yarn test

      # - name: Run Go Automated Tests
      #   run: |
      #     cd /workspaces/terraform-provider-corellium
      #     go get
      #     go mod tidy
      #     go install .
      #     TF_ACC=1 go test -v ./...
